# name: Daily ingestion

# on:
#   schedule:
#     # GitHub utilise l'UTC.
#     # Impossible d'adapter automatiquement l'heure d'été
#     - cron: '59 21 * * *'   # ≈ 23:59 en été
#   workflow_dispatch:        # Lancer manuellement si besoin

# jobs:
#   run-script:
#     runs-on: ubuntu-latest
#     concurrency:
#       group: daily-newsdata
#       cancel-in-progress: false

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install deps
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run main.py
#         env:
#           NEWSDATA_API_KEY: ${{ secrets.NEWSDATA_API_KEY }}
#           PGHOST: ${{ secrets.PGHOST }}
#           PGPORT: ${{ secrets.PGPORT }}
#           PGDATABASE: ${{ secrets.PGDATABASE }}
#           PGUSER: ${{ secrets.PGUSER }}
#           PGPASSWORD: ${{ secrets.PGPASSWORD }}
#         run: |
#           python main.py
